/****** ADMISSÃO, INTERNAÇÃO e PACIENTE  ******/
CREATE TABLE [SIS_INTERNACAO]
(
	[CD_INTERNACAO] INT NOT NULL PRIMARY KEY IDENTITY (1, 1),
	[CD_PACIENTE] INT NOT NULL,
	[NM_ATENDIMENTO] INT NOT NULL,
	[CD_PARAMETROS_BASE] INT NOT NULL,
	[DT_INTERNACAO] DATETIME NOT NULL,
	[DT_CADASTRO] DATETIME NOT NULL,
	[DT_DESATIVACAO] DATETIME,
	[BL_DESATIVACAO] BIT NOT NULL

	FOREIGN KEY (CD_PARAMETROS_BASE) REFERENCES SIS_PARAMETROS_BASE(CD_PARAMETROS_BASE),	
	FOREIGN KEY (CD_PACIENTE) REFERENCES SIS_PACIENTE(CD_PACIENTE)
)


CREATE TABLE [SIS_ADMISSAO]
(
	[CD_ADMISSAO] INT NOT NULL PRIMARY KEY IDENTITY (1, 1),
	[CD_INTERNACAO] INT NOT NULL,
	[CD_SETOR] INT NOT NULL,
	[CD_LEITO] INT,
	[DT_ADMISSAO] DATETIME NOT NULL,
	[DT_CADASTRO] DATETIME NOT NULL,
	[DT_DESATIVACAO] DATETIME,
	[BL_DESATIVACAO] BIT NOT NULL

	FOREIGN KEY (CD_SETOR) REFERENCES SEG_SETOR(CD_SETOR),
	FOREIGN KEY (CD_INTERNACAO) REFERENCES SIS_INTERNACAO(CD_INTERNACAO),
	FOREIGN KEY (CD_LEITO) REFERENCES SEG_LEITO(CD_LEITO)
)


ALTER TABLE SIS_PACIENTE
  ADD CD_ESTABELECIMENTO INT NOT NULL DEFAULT(18)
  FOREIGN KEY (CD_ESTABELECIMENTO) REFERENCES SEG_ESTABELECIMENTO_SAUDE(CD_ESTABELECIMENTO)



/****** DISPOSITIVOS DA INTERNAÇÃO   ******/
  CREATE TABLE [SIS_CATEGORIA_DISPOSITIVO]
(
	[CD_CATEGORIA_DISPOSITIVO] INT NOT NULL PRIMARY KEY, 
    [TX_DESCRICAO] VARCHAR(100) NOT NULL, 
    [DT_CADASTRO] DATETIME NOT NULL, 
    [DT_DESATIVACAO] DATETIME NULL
)

  CREATE TABLE [SIS_TIPO_DISPOSITIVO]
(
	[CD_TIPO_DISPOSITIVO] INT NOT NULL PRIMARY KEY, 
	[CD_CATEGORIA_DISPOSITIVO] INT NOT NULL, 
    [TX_DESCRICAO] VARCHAR(100) NOT NULL, 
    [DT_CADASTRO] DATETIME NOT NULL, 
    [DT_DESATIVACAO] DATETIME NULL

	FOREIGN KEY (CD_CATEGORIA_DISPOSITIVO) REFERENCES SIS_CATEGORIA_DISPOSITIVO(CD_CATEGORIA_DISPOSITIVO)
)

  CREATE TABLE [SIS_SITIO_DISPOSITIVO]
(
	[CD_SITIO_DISPOSITIVO] INT NOT NULL PRIMARY KEY, 
	[CD_TIPO_DISPOSITIVO] INT NOT NULL, 
    [TX_DESCRICAO] VARCHAR(100) NOT NULL, 
    [DT_CADASTRO] DATETIME NOT NULL, 
    [DT_DESATIVACAO] DATETIME NULL

	FOREIGN KEY (CD_TIPO_DISPOSITIVO) REFERENCES SIS_TIPO_DISPOSITIVO(CD_TIPO_DISPOSITIVO)
)

  CREATE TABLE [SIS_SIGLA_DISPOSITIVO]
(
	[CD_SIGLA_DISPOSITIVO] INT NOT NULL PRIMARY KEY, 
	[CD_TIPO_DISPOSITIVO] INT NOT NULL, 
	[CD_SITIO_DISPOSITIVO] INT NOT NULL, 
	[CD_LATERALIDADE] INT NOT NULL, 
    [TX_SIGLA] VARCHAR(50) NOT NULL, 
    [DT_CADASTRO] DATETIME NOT NULL, 
    [DT_DESATIVACAO] DATETIME NULL

	FOREIGN KEY (CD_TIPO_DISPOSITIVO) REFERENCES SIS_TIPO_DISPOSITIVO(CD_TIPO_DISPOSITIVO),	
	FOREIGN KEY (CD_SITIO_DISPOSITIVO) REFERENCES SIS_SITIO_DISPOSITIVO(CD_SITIO_DISPOSITIVO)
)


  CREATE TABLE [SIS_DISPOSITIVO_INTERNACAO]
(
	[CD_DISPOSITIVO_INTERNACAO] INT NOT NULL PRIMARY KEY, 
	[CD_SIGLA_DISPOSITIVO] INT NOT NULL, 
	[CD_INTERNACAO] INT NOT NULL, 
    [DT_IMPLANTE] DATETIME NOT NULL,
    [DT_RETIRADA] DATETIME, 
    [DT_CADASTRO] DATETIME NOT NULL, 
    [DT_DESATIVACAO] DATETIME NULL

	FOREIGN KEY (CD_SIGLA_DISPOSITIVO) REFERENCES SIS_SIGLA_DISPOSITIVO(CD_SIGLA_DISPOSITIVO),	
	FOREIGN KEY (CD_INTERNACAO) REFERENCES SIS_INTERNACAO(CD_INTERNACAO)
)


/****** DIAGNÓSTICOS E COMORBIDADES DA INTERNAÇÃO   ******/
USE DB_MEDNOTE_HOMOLOG

CREATE TABLE [SIS_CATEGORIA_DIAGNOSTICO]
(
	[CD_CATEGORIA_DIAGNOSTICO] INT NOT NULL PRIMARY KEY, 
	[CD_TIPO_INTERNACAO] INT NOT NULL, 
	[CD_TIPO_DIAGNOSTICO] INT NOT NULL, 
    [TX_DESCRICAO] VARCHAR(100) NOT NULL, 
    [DT_CADASTRO] DATETIME NOT NULL, 
    [DT_DESATIVACAO] DATETIME NULL,
	[BL_DESATIVADO] BIT NOT NULL
)

  CREATE TABLE [SIS_DIAGNOSTICO]
(
	[CD_DIAGNOSTICO] INT NOT NULL PRIMARY KEY, 
	[CD_CATEGORIA_DIAGNOSTICO] INT NOT NULL, 
    [TX_DESCRICAO] VARCHAR(100) NOT NULL, 
    [DT_CADASTRO] DATETIME NOT NULL, 
    [DT_DESATIVACAO] DATETIME NULL,
	[BL_DESATIVADO] BIT NOT NULL

	FOREIGN KEY (CD_CATEGORIA_DIAGNOSTICO) REFERENCES SIS_CATEGORIA_DIAGNOSTICO(CD_CATEGORIA_DIAGNOSTICO)
)  

CREATE TABLE [SIS_DIAGNOSTICO_PRIMARIO]
(
	[CD_DIAGNOSTICO_PRIMARIO] INT NOT NULL PRIMARY KEY, 
	[CD_DIAGNOSTICO] INT NOT NULL, 
	[CD_INTERNACAO] INT NOT NULL, 
	[CD_ORIGEM] INT NOT NULL, 
    [DT_CADASTRO] DATETIME NOT NULL, 
    [DT_DESATIVACAO] DATETIME NULL,
	[BL_DESATIVADO] BIT NOT NULL
	
	FOREIGN KEY (CD_DIAGNOSTICO) REFERENCES SIS_DIAGNOSTICO(CD_DIAGNOSTICO),
	FOREIGN KEY (CD_INTERNACAO) REFERENCES SIS_INTERNACAO(CD_INTERNACAO)
)

CREATE TABLE [SIS_COMPLICACAO_DIAGNOSTICO]
(
	[CD_COMPLICACAO_DIAGNOSTICO] INT NOT NULL PRIMARY KEY, 
	[CD_DIAGNOSTICO] INT NOT NULL, 
	[CD_INTERNACAO] INT NOT NULL,
    [DT_DIAGNOSTICO] DATETIME NOT NULL,
    [DT_CADASTRO] DATETIME NOT NULL, 
    [DT_DESATIVACAO] DATETIME NULL,
	[BL_DESATIVADO] BIT NOT NULL
	
	FOREIGN KEY (CD_DIAGNOSTICO) REFERENCES SIS_DIAGNOSTICO(CD_DIAGNOSTICO),
	FOREIGN KEY (CD_INTERNACAO) REFERENCES SIS_INTERNACAO(CD_INTERNACAO)
)

CREATE TABLE [SIS_COMORBIDADE_INTERNACAO]
(
	[CD_COMORBIDADE_INTERNACAO] INT NOT NULL PRIMARY KEY, 
	[CD_INTERNACAO] INT NOT NULL,
	[CD_COMORBIDADE] INT NOT NULL, 
    [DT_CADASTRO] DATETIME NOT NULL, 
    [DT_DESATIVACAO] DATETIME NULL,
	[BL_DESATIVADO] BIT NOT NULL
	
	FOREIGN KEY (CD_INTERNACAO) REFERENCES SIS_INTERNACAO(CD_INTERNACAO)
)

/****** CONFIGURAÇÕES DO CLIENTE    ******/

CREATE TABLE [SEG_TIPO_SETOR_CLIENTE](
	[CD_TIPO_SETOR_CLIENTE] INT IDENTITY(1,1) NOT NULL,
	[CD_CLIENTE] INT NOT NULL,
	[CD_TIPO_SETOR] INT NOT NULL,
	[DT_CADASTRO] DATETIME NOT NULL,
	[DT_DESATIVACAO] DATETIME,
	[BL_DESATIVACAO] BIT NOT NULL

	FOREIGN KEY (CD_CLIENTE) REFERENCES SEG_CLIENTE(CD_CLIENTE),	
	FOREIGN KEY (CD_TIPO_SETOR) REFERENCES SEG_TIPO_SETOR(CD_TIPO_SETOR)
)

CREATE TABLE [SEG_SETOR_USUARIO](
	[CD_SETOR_USUARIO] INT IDENTITY(1,1) NOT NULL,
	[CD_USUARIO] INT NOT NULL,
	[CD_SETOR] INT NOT NULL,
	[DT_CADASTRO] DATETIME NOT NULL,
	[DT_DESATIVACAO] DATETIME,
	[BL_DESATIVACAO] BIT NOT NULL

	FOREIGN KEY (CD_USUARIO) REFERENCES SEG_USUARIO(CD_USUARIO),	
	FOREIGN KEY (CD_SETOR) REFERENCES SEG_SETOR(CD_SETOR)
)